### ISSUE TITLE
BH 1.87.0-0 release candidate and six indentified isse

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/bh#103]
Boost release 1.87.0 two days ago, and I prepared R package BH 1.87.0-0 with the usual patching for CRAN, and run a full-reverse dependency check.   The following six packages have shown to not pass the check, and we will need look into possibly smoothing this before a CRAN upload, likely in January (assuming another CRAN winter closure as in previous years).

- [ ] [GeoFIS](https://www.geofis.org/en/) (website) email sent 2024-12-13
- [ ] [OwenQ](https://github.com/stla/OwenQ) (test errors), [issue](https://github.com/stla/OwenQ/issues/4) filed 2024-12-14
- [ ] [RcppUUID](https://gitlab.com/artemklevtsov/rcppuuid/) (Gitlab) opened [issue](https://gitlab.com/artemklevtsov/rcppuuid/-/issues/2) with patch 2024-12-13
- [x] [rxode2](https://github.com/nlmixr2/rxode2/) fixed in version 3.0.3 on CRAN 2024-12-15
- [x] [rxode2ll](https://github.com/nlmixr2/rxode2ll) fixed in version 2.0.13 on CRAN 2024-12-15
- [ ] [TDA](https://github.com/compTAG/r-tda) filed [issue](https://github.com/compTAG/r-tda/issues/43) 2024-12-15

Following what we did in issues #100 for 1.84.0, #88 for 1.81.0, #80 for 1.78.0, #76 for 1.75.0, ... I plan to open issues and (if possible) prepare PRs but otherwise may have to rely on maintainer cooperation as before.  

The pre-release is now ~/ will be~ available at my R-universe, see https://eddelbuettel.r-universe.dev/BH.  Also CCing maintainers for which I have GitHub handles directly:  @stla @artemklevtsov @mattfidler @jkim82133 --- your cooperation will be appreciated, as always.

**Comment by mattfidler** [comment]
Hi @eddelbuettel  I can't reproduce an issue with `rxode2ll` `v2.0.12`, it seems to be running a slightly different version of R-universe:

```
other attached packages:
[1] BH_1.84.0-0.1
```

which matches what I expect from the github repo.

**Comment by eddelbuettel** [comment]
BH 1.87.0-1 is now arriving at CRAN.

**Comment by eddelbuettel** [comment]
Thanks to @jkin82133 for getting a fixed TDA 1.9.4 on CRAN, much appreciated!
