### ISSUE TITLE
BH 1.81.0 upgrade plan

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/bh#88]
Boost released 1.81.0 this week, and the BH package was updated to release 1.81.0-0 in PR #87.  It can be accessed from the [ghrr drat](https://ghrr.github.io/drat/) via 

    install.packages("BH", repos=c("https://ghrr.github.io/drat", "https://cloud.r-project.org"))

and similarly from [r-universe](https://eddelbuettel.r-universe.dev/ui#package:BH). As usual we ran full reverse-dependency checks on Debian testing system (where gcc-12 is the default).  The logs are [in this commit at the rcpp-logs repo](https://github.com/RcppCore/rcpp-logs/commit/995963ce25fd8480f2a3b8a9564df37c5abdfd62) are reveal issues in these six packages 

- [ ] colourvalues  (2 out of 523 tests fail) (maintainer emailed 2022-12-15) ([PR #77](https://github.com/SymbolixAU/colourvalues/pull/77) made 2022-12-19) (heard back 2022-12-21 'mid-January should work') (merged 2022-12-29)
- [ ] httpgd  (compilation error on string_view) (maitainer emailed 2022-12-15) (heard back 2022-12-16, package fix by January planned)
- [ ] rgeoda (compilation error, possibly only missing an include) (unrelated to BH, g++-12 issue) ([PR #4 ](https://github.com/GeoDaCenter/libgeoda/pull/4) made 2022-12-16 in related library repo) (merged 2023-01-01)
- [x] rlas (compilation issue from g++-12?) (unrelated to BH, g++-12 issue) ([PR #57](https://github.com/r-lidar/rlas/pull/57) made 2022-12-16) (merged 2022-12-16) (version 1.6.2 on CRAN 2023-01-06)
- [x] rstan (possibly more complex Boost Phoenix issue) (maintainer emailed 2022-12-16) (heard back 2022-12-16: 'soon') (heard back 2022-12-26 linker issue addressed, rest possibly more involved) (version 2.21.8 on CRAN 2023-01-17)
- [ ] TDA (issue with Boost's `vector`) (maintainer emailed 2022-12-16) (heard back 2022-12-26, 'January should be fine')

I have or will contact all maintainers by either email or PR.  The plan would be to get all packages fixed in four weeks from now to permit a mid-January CRAN upload of BH 1.81.0.

Edit 2022-12-30 We now have 1.81.0-1 (via #90) which had another round of reverse-depends checks which revealed no new or changed issue.

**Comment by nx10** [comment]
I just submitted `httpgd` 1.3.1 which should resolve this issue: http://nx10.github.io/cransubs/pkg#httpgd

If anyone is interested in [the fix](https://github.com/nx10/httpgd/commit/6e094f409e21e38bad598a9aab630ec07b34f33d), boost::beast string views switched internally from [boost::detail::basic_string_view](https://www.boost.org/doc/libs/1_81_0/boost/utility/string_view.hpp) to [boost::core::basic_string_view](https://www.boost.org/doc/libs/1_81_0/boost/core/detail/string_view.hpp) in the latest version. Of these the current one does not have a .to_string() method.

**Comment by eddelbuettel** [comment]
Thank you so much, also for the added color.  I have seen `boost::core::*` pop up in the context of the 'grand ole sprintf replacement' as there is a (pending/coming) `boost::core::snprintf` that I aded in 1.81.0-1 in order to minimize that issue.

(And good luck with CRAN. I always found them reasonable when I replied on such false positives.  And an updated BH will be coming if all goes well by mid-Jan.  Speaking of which, any update from the stan world @bgoodri ?)

**Comment by bgoodri** [comment]
I have a real fix. Just testing the reverse dependencies.

**Comment by eddelbuettel** [comment]
I would like to upload BH in the next few days.  Of the six packages, only one (`rlas`) made it through.  Uploading may help another (`httpgd`).  I hope it may help `rstan`, `colorvalues`, `TDA`.

Thoughts?

**Comment by bgoodri** [comment]
I uploaded rstan to CRAN. It should be fine, but won't be approved until tomorrow at the earliest.

**Comment by eddelbuettel** [comment]
Cool, thanks for the update!  I will try to follow-up with BH and we can continue to coordinate here.

**Comment by nx10** [comment]
Seems like [BH 1.81 is now on CRAN](https://cran.r-project.org/package=BH). `httpgd` will follow up shortly

**Comment by eddelbuettel** [comment]
Correct.  It is now up on CRAN, I mentioned this issue, the two closed one and your 'pending' `httpgd` as open but imminently addressable and so it was moved ahead by the CRAN maintainers after a few days.

I will close this issue as completed, we can still discuss here needed.

Big big thanks to everybody for the prompt help.

**Comment by eddelbuettel** [comment]
@nx10:  Yay!

![image](https://user-images.githubusercontent.com/673121/215500198-2eecec8a-4c80-4da2-a828-182b0d0b9e16.png)

Glad to see it back!

**Comment by nx10** [comment]
Thanks! They requested a couple documentation changes so it got delayed again. 2.0 soon™
